"""BrokerClient protocol — abstract interface for broker interactions."""

from __future__ import annotations

from typing import Protocol


class BrokerClient(Protocol):
    """Protocol for all broker interactions.

    Implementations: WebullCLIAdapter (subprocess), future MCP or SDK adapters.
    Business logic must depend only on this protocol, never on a specific transport.
    """

    def preview_order(self, account_id: str, order_json: dict) -> dict: ...
    def place_order(self, account_id: str, order_json: dict) -> dict: ...
    def get_order_status(self, account_id: str, order_id: str) -> dict: ...
    def cancel_order(self, account_id: str, order_id: str) -> dict: ...
    def get_account_list(self) -> list[dict]: ...
    def get_balance(self, account_id: str) -> dict: ...
    def get_positions(self, account_id: str) -> list[dict]: ...
    def get_open_orders(self, account_id: str) -> list[dict]: ...
